version: "3"

services:

  mailsender:
    build: ./mailsender
    container_name: mailsender
    
  meteo:
    build: .email/modules/meteo
    container_name: meteo

  news:
    build: .email/modules/news
    container_name: news

  mailbuilder:
    build: ./mailsender
    container_name: mailsender
    depends_on: 
      - meteo
      - news
      - mailsender
    


