version: "3"

services:

  mailsender:
    build: ./email/mailsender
    container_name: mailsender

  meteo:
    build: ./email/modules/meteo
    container_name: meteo

  news:
    build: ./email/modules/news
    container_name: news

  mailbuilder:
    build: ./email/mailbuilder
    container_name: mailbuilder
    depends_on: 
      - meteo
      - news
      - mailsender